### ISSUE TITLE
Exception when running application

### ISSUE THREAD

**Issue by kishimoto-tsuneyo** [stephenmac7/furitsuki#1]
Here's the error:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/atilika/kuromoji/unidic/Tokenizer : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at com.stephenmac7.jcore.UnidicImporter$.<init>(UnidicImporter.scala:26)
	at com.stephenmac7.jcore.UnidicImporter$.<clinit>(UnidicImporter.scala)
	at com.stephenmac7.furitsuki.Main$.main(Main.scala:29)
	at com.stephenmac7.furitsuki.Main.main(Main.scala)
```

**Comment by kishimoto-tsuneyo** [comment]
It runs with the current Oracle JDK.
